version: "3.8"

services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - GITHUB_ACTIONS=false
    depends_on:
      - redis
      - rabbitmq
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP (Python koduyla haberleşme)
      - "15672:15672"    # Web UI (tarayıcıdan yönetim arayüzü)
    restart: always
